import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryClientProvider } from "@/context/query";

const font = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          font.className,
          "bg-gray-50 flex justify-center items-center"
        )}
      >
        <QueryClientProvider>
          <main className="bg-white w-[450px] min-h-screen relative">
            {children}
          </main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
